[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[project]
name = "asm_builtins"
description = "Builtins rewrite in ASM"
version = "0.1.0"

[tool.setuptools]
ext-modules = [
  { name = "asm_builtins", sources = ["asm_builtins/mod.c"] }
]
